# secret
apiVersion: v1
kind: Secret
metadata:
  name: celery-workers-secret
type: Opaque
data:
  CELERY_BROKER_URL: YW1xcDovL2FkbWluOnNlY3JldHBhc3N3b3JkQHJhYmJpdG1xLnJhYmJpdG1xOjU2NzI= #amqp://admin:secretpassword@rabbitmq.rabbitmq:5672
  CELERY_RESULT_BACKEND: ZGIrcG9zdGdyZXNxbDovL3Rlc3Q6dGVzdEAxMjNAcG9zdGdyZXNxbC5wb3N0Z3Jlczo1NDMyL2ZsYXNrLXNlcnZpY2U= # db+postgresql://test:test@123@postgresql.postgres:5432/flask-service
  SECRET_KEY: dGVzdA== # test
---
# deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
spec:
  replicas: 0
  selector:
    matchLabels:
      name: celery-worker
  template:
    metadata:
      labels:
        name: celery-worker
    spec:
      containers:
        - name: celery-worker
          image: jerryhuang1204/celery-k8s:0.0.3
          command:
            - "bash"
            - "-c"
            - "celery -A main.celery worker -l info -c 1"
          envFrom:
            - secretRef:
                name: celery-workers-secret
          env:
            - name: SLEEP_TIME
              value: '30'
---

