# secret
apiVersion: v1
kind: Secret
metadata:
  name: flask-secret
type: Opaque
data:
  CELERY_BROKER_URL: YW1xcDovL2FkbWluOnNlY3JldHBhc3N3b3JkQHJhYmJpdG1xLnJhYmJpdG1xOjU2NzI=
  CELERY_RESULT_BACKEND: ZGIrcG9zdGdyZXNxbDovL3Rlc3Q6dGVzdEAxMjNAcG9zdGdyZXNxbC5wb3N0Z3Jlczo1NDMyL2ZsYXNrLXNlcnZpY2U=
  SECRET_KEY: dGVzdA==
---
# deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-server
spec:
  replicas: 1
  selector:
    matchLabels:
      name: flask-server
  template:
    metadata:
      labels:
        name: flask-server
    spec:
      containers:
        - name: flask-server
          image: jerryhuang1204/celery-k8s:0.0.4
          envFrom:
            - secretRef:
                name: flask-secret
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              name: rest
          resources:
            limits:
              cpu: "100m"
              memory: "100Mi"
            requests:
              cpu: "30m"
              memory: "30Mi"
---
# service
apiVersion: v1
kind: Service
metadata:
  name: flask-server
spec:
  type: LoadBalancer
  selector:
    name: flask-server
  ports:
    - port: 80
      targetPort: rest