apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: celery-worker-scaler
spec:
  scaleTargetRef:
    name: celery-worker
  pollingInterval: 3
  cooldownPeriod: 120
  minReplicaCount: 0
  maxReplicaCount: 100
  advanced:
    restoreToOriginalReplicaCount: false
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 120
          policies:
          - type: Percent
            value: 100
            periodSeconds: 15

  triggers:
    - type: rabbitmq
      metadata:
        queueName: celery
        queueLength: "1"
      authenticationRef:
        name: rabbitmq-worker-trigger
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: rabbitmq-worker-trigger
spec:
  secretTargetRef:
    - parameter: host
      name: celery-workers-secret
      key: CELERY_BROKER_URL
